const Map<String, String> mapPlaceType = {
  "lodging": "숙박 시설",
  "restaurant": "음식점",
  "store": "상점",
  "airport": "공항",
  "park": "공원",
  "bank": "은행",
  "university": "대학교",
  "hospital": "병원",
  "bus_station": "버스 정류장",
  "train_station": "기차역",
  "subway_station": "지하철역",
  "shopping_mall": "쇼핑몰",
  "museum": "박물관",
  "library": "도서관",
  "zoo": "동물원",
  "amusement_park": "놀이공원",
  "aquarium": "수족관",
  "art_gallery": "미술관",
  "tourist_attraction": "관광지",
  "stadium": "경기장",
  "church": "교회",
  "mosque": "모스크",
  "synagogue": "시나고그",
  "hindu_temple": "힌두 사원",
  "parking": "주차장",
};
